import os
import uuid
import json
import re
import sqlite3
import statistics
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

DB_PATH = "provenance.db"


def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            content_id TEXT NOT NULL,
            creator_id TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            text_snippet TEXT,
            content_type TEXT DEFAULT 'text',
            attribution TEXT NOT NULL,
            confidence REAL NOT NULL,
            llm_score REAL,
            stylo_score REAL,
            burstiness_score REAL,
            transparency_label TEXT,
            status TEXT DEFAULT 'classified',
            appeal_reasoning TEXT,
            appeal_timestamp TEXT
        )
    """)
    # Migrate existing DBs that lack new columns
    for col, definition in [
        ("burstiness_score", "REAL"),
        ("content_type", "TEXT DEFAULT 'text'"),
    ]:
        try:
            conn.execute(f"ALTER TABLE audit_log ADD COLUMN {col} {definition}")
        except sqlite3.OperationalError:
            pass

    conn.execute("""
        CREATE TABLE IF NOT EXISTS certificates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            certificate_id TEXT NOT NULL UNIQUE,
            content_id TEXT NOT NULL,
            creator_id TEXT NOT NULL,
            human_statement TEXT NOT NULL,
            issued_at TEXT NOT NULL,
            verified_label TEXT NOT NULL
        )
    """)
    conn.commit()
    conn.close()


init_db()


# ── Signal 1: LLM classification via Groq ─────────────────────────────────────

def llm_signal(text: str) -> float:
    """
    Sends text to llama-3.3-70b-versatile and asks for an AI-probability score.
    Returns 0.0 (human) to 1.0 (AI). Falls back to 0.5 on any error.
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    prompt = (
        "You are an expert at detecting AI-generated text. Analyze the text below "
        "and estimate the probability it was generated by an AI language model rather "
        "than written by a human.\n\n"
        "Consider: uniformity of sentence structure, vocabulary diversity, hedging "
        "phrases typical of LLMs, presence of genuine personal voice, and natural "
        "stylistic irregularities that signal human authorship.\n\n"
        'Respond with ONLY valid JSON in this exact format: '
        '{"ai_probability": <float 0.0-1.0>, "reasoning": "<one sentence>"}\n\n'
        f'Text:\n"""\n{text[:2000]}\n"""'
    )
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r'\{.*\}', raw, re.DOTALL)
        if match:
            data = json.loads(match.group())
            score = float(data.get("ai_probability", 0.5))
            return max(0.0, min(1.0, score))
    except Exception:
        pass
    return 0.5


# ── Signal 2: Stylometric heuristics ──────────────────────────────────────────

def stylo_signal(text: str) -> float:
    """
    Measures three structural properties that differ between human and AI writing.
    Returns 0.0 (human-like) to 1.0 (AI-like).

    AI text is more uniform in sentence length, has lower vocabulary diversity,
    and ends sentences with periods at a more consistent rate.
    """
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s for s in sentences if len(s.split()) >= 2]
    words = re.findall(r'\b[a-zA-Z]+\b', text.lower())

    if len(sentences) < 2 or not words:
        return 0.5

    # Feature 1: sentence-length variance — low variance suggests AI uniformity
    lengths = [len(s.split()) for s in sentences]
    variance = statistics.variance(lengths)
    variance_score = 1.0 - min(variance / 30.0, 1.0)

    # Feature 2: type-token ratio — lower TTR at length suggests AI repetition
    ttr = len(set(words)) / len(words)
    ttr_score = 1.0 - min(ttr / 0.8, 1.0)

    # Feature 3: period-ending ratio — AI writes more grammatically complete sentences
    period_ratio = sum(1 for s in sentences if s.strip().endswith('.')) / len(sentences)
    punct_score = period_ratio

    return max(0.0, min(1.0, 0.4 * variance_score + 0.4 * ttr_score + 0.2 * punct_score))


# ── Signal 3: AI linguistic pattern density (ensemble stretch) ────────────────

# Phrase patterns disproportionately common in AI-generated formal prose
_AI_HEDGE_PATTERNS = [
    r'\bfurthermore\b', r'\badditionally\b', r'\bmoreover\b',
    r'\bit is important\b', r'\bit is essential\b', r'\bit is crucial\b',
    r'\bit should be noted\b', r'\bit is worth noting\b',
    r'\bin conclusion\b', r'\bin summary\b', r'\bin order to\b',
    r'\bit is necessary\b', r'\bone must\b', r'\bthis ensures\b',
    r'\bthis allows\b', r'\bthis enables\b', r'\bthis facilitates\b',
    r'\bit is important to note\b', r'\bit is essential to\b',
]


def burstiness_signal(text: str) -> float:
    """
    Measures two linguistic pattern properties that are genuinely independent
    of both the LLM's holistic judgment (Signal 1) and sentence-level structure
    (Signal 2):

    1. Sentence-starter repetition: AI text frequently reuses a small set of
       sentence-opening words ('It', 'The', 'This', 'Furthermore', 'Moreover').
       Lower variety of first-words → more AI-like.

    2. Boilerplate phrase density: AI formal prose uses hedging/transitional
       phrases ('it is important to', 'furthermore', 'in conclusion',
       'this enables') at a measurably higher rate than human writing.
       Higher density per 100 words → more AI-like.

    Returns 0.0 (human-like) to 1.0 (AI-like).
    Blind spots: academic human writing may contain some transitional phrases;
    very short texts with fewer than 3 sentences return neutral (0.5).
    """
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s.strip() for s in sentences if len(s.split()) >= 3]
    words = re.findall(r'\b[a-zA-Z]+\b', text.lower())

    if len(sentences) < 3 or len(words) < 30:
        return 0.5

    # Feature 1: sentence-starter repetition
    starters = [s.split()[0].lower() for s in sentences if s.split()]
    if not starters:
        return 0.5
    unique_ratio = len(set(starters)) / len(starters)
    # All unique starters → human-like (0.0); many repeats → AI-like (1.0)
    starter_score = max(0.0, min(1.0, 1.0 - unique_ratio))

    # Feature 2: boilerplate phrase density (occurrences per 100 words)
    total_words = max(len(words), 1)
    phrase_count = sum(
        len(re.findall(pattern, text.lower()))
        for pattern in _AI_HEDGE_PATTERNS
    )
    density = phrase_count / total_words * 100
    # Human text typically < 1 per 100 words; AI formal prose typically ≥ 2–3
    density_score = min(1.0, density / 3.0)

    return round(0.5 * starter_score + 0.5 * density_score, 4)


# ── Metadata signals (multi-modal stretch) ────────────────────────────────────

def metadata_llm_signal(metadata: dict) -> float:
    """
    Asks Groq whether structured content metadata looks AI-generated.
    Captures generic phrasings in titles/descriptions that humans rarely use.
    Returns 0.0 (human) to 1.0 (AI).
    """
    meta_text = f"Title: {metadata.get('title', '')}\n"
    meta_text += f"Description: {metadata.get('description', '')}\n"
    tags = metadata.get('tags', [])
    if tags:
        meta_text += f"Tags: {', '.join(str(t) for t in tags)}\n"
    if metadata.get('word_count'):
        meta_text += f"Word count: {metadata['word_count']}\n"

    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    prompt = (
        "You are an expert at detecting AI-generated content metadata. "
        "Analyze the following metadata and estimate the probability it was "
        "generated by an AI rather than written by a human creator.\n\n"
        "Consider: whether the title is formulaic or organic, whether the "
        "description uses generic AI phrases like 'this piece explores' or "
        "'a journey of', whether the tags are exhaustively systematic or "
        "selectively personal.\n\n"
        'Respond with ONLY valid JSON: {"ai_probability": <float 0.0-1.0>, "reasoning": "<one sentence>"}\n\n'
        f"Metadata:\n{meta_text[:1500]}"
    )
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()
        match = re.search(r'\{.*\}', raw, re.DOTALL)
        if match:
            data = json.loads(match.group())
            return max(0.0, min(1.0, float(data.get("ai_probability", 0.5))))
    except Exception:
        pass
    return 0.5


def metadata_structural_signal(metadata: dict) -> float:
    """
    Analyzes structural properties of metadata that differ between AI and human creators:

    1. Personal pronoun absence in description — human creators more often use
       'I', 'my', 'we' when describing their own work; AI-generated descriptions
       are typically in the third person or impersonal.

    2. Generic AI phrase detection — a curated list of phrases that LLMs
       disproportionately use in content summaries.

    3. Tag count — AI tends to produce exhaustive, systematic tag lists;
       humans pick a small, specific set.

    Returns 0.0 (human-like) to 1.0 (AI-like).
    """
    description = metadata.get('description', '').lower()
    tags = metadata.get('tags', [])

    # Feature 1: personal pronoun ratio — more pronouns → more human
    personal_pronouns = len(re.findall(r'\b(i|my|me|we|our|mine|ours)\b', description))
    word_count = max(len(description.split()), 1)
    pronoun_ratio = personal_pronouns / word_count
    # High ratio (> 0.04) → human; 0 → more AI-like
    pronoun_score = max(0.0, min(1.0, 1.0 - (pronoun_ratio / 0.04)))

    # Feature 2: generic AI phrases in description
    ai_phrases = [
        'this piece explores', 'this work delves into', 'a journey of',
        'the intersection of', 'this story follows', 'through the lens of',
        'a tale of', 'navigating the complexities', 'in this compelling',
        'this narrative explores', 'a powerful exploration',
    ]
    phrase_count = sum(1 for phrase in ai_phrases if phrase in description)
    phrase_score = min(1.0, phrase_count / 2.0)

    # Feature 3: tag count
    tag_count = len(tags)
    # 1–3 tags → human-like; 8+ → AI-like (systematic coverage)
    tag_score = min(1.0, max(0.0, (tag_count - 3) / 6.0))

    return round(0.4 * pronoun_score + 0.4 * phrase_score + 0.2 * tag_score, 4)


# ── Confidence scoring ─────────────────────────────────────────────────────────

def combine_signals(llm_score: float, stylo_score: float,
                    burstiness_score: float) -> float:
    """
    Ensemble weighted average over three independent signals.

    Weights (0.70 / 0.20 / 0.10):
    - LLM carries the most weight: it captures semantic coherence holistically.
    - Stylometric is second: sentence-level structural patterns are reliable at
      scale but degrade on short texts.
    - Linguistic pattern signal is third: phrase-density detection is an
      independent corroborating layer; returns 0.5 (neutral) for texts with
      fewer than 3 sentences, so very short submissions aren't penalised.

    Conflict resolution: when signals disagree, the LLM's holistic judgment
    dominates. A split (e.g. LLM=0.8, stylo=0.3, burstiness=0.4) still
    produces a meaningful ensemble score (0.8×0.70 + 0.3×0.20 + 0.4×0.10 =
    0.660) that lands in the uncertain zone rather than forcing a binary flip.
    """
    return round(0.70 * llm_score + 0.20 * stylo_score + 0.10 * burstiness_score, 4)


def combine_metadata_signals(llm_score: float, struct_score: float) -> float:
    """Weighted average for metadata content type (no burstiness signal)."""
    return round(0.60 * llm_score + 0.40 * struct_score, 4)


def get_attribution(confidence: float) -> str:
    """
    Asymmetric thresholds: require stronger evidence to label content AI-generated
    than to label it human, because false positives harm creators more than
    false negatives harm the platform.
    """
    if confidence >= 0.75:
        return "likely_ai"
    elif confidence <= 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ── Transparency labels ────────────────────────────────────────────────────────

_LABEL_TEMPLATES = {
    "likely_ai": (
        "AI-Assisted Content Detected — High Confidence ({pct}%)\n"
        "Our system found strong signals of AI-generated writing in this submission, "
        "including uniform sentence structure and phrasing patterns typical of language models. "
        "This label does not prevent the content from being shared, but is shown to readers for context. "
        "If you are the human author of this work and believe this is incorrect, "
        "you may submit an appeal and a human reviewer will examine your case."
    ),
    "likely_human": (
        "Original Human Authorship — High Confidence ({pct}%)\n"
        "Our system found strong signals of human authorship in this submission: "
        "natural variation in sentence rhythm, vocabulary diversity, and stylistic "
        "irregularities consistent with original human writing. "
        "No AI-generation label is shown to readers."
    ),
    "uncertain": (
        "Origin Unclear — Further Review May Be Needed ({pct}% confidence)\n"
        "Our system detected a mixed signal and could not confidently determine "
        "whether this content was written by a human or generated by AI. "
        "It may be human-written, AI-assisted, or AI-generated with heavy human editing. "
        "Out of caution, this content is not labeled as AI-generated. "
        "If you feel the ambiguity reflects poorly on your work, "
        "you may submit an appeal to request human review."
    ),
}


def generate_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)
    return _LABEL_TEMPLATES[attribution].format(pct=pct)


# ── Database helpers ───────────────────────────────────────────────────────────

def log_submission(content_id, creator_id, snippet, content_type,
                   attribution, confidence, llm_score, stylo_score,
                   burstiness_score, label):
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """INSERT INTO audit_log
           (content_id, creator_id, timestamp, text_snippet, content_type,
            attribution, confidence, llm_score, stylo_score, burstiness_score,
            transparency_label, status)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'classified')""",
        (content_id, creator_id, datetime.now(timezone.utc).isoformat(),
         snippet, content_type, attribution, confidence,
         llm_score, stylo_score, burstiness_score, label),
    )
    conn.commit()
    conn.close()


def update_appeal(content_id, reasoning):
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """UPDATE audit_log
           SET status = 'under_review',
               appeal_reasoning = ?,
               appeal_timestamp = ?
           WHERE content_id = ?""",
        (reasoning, datetime.now(timezone.utc).isoformat(), content_id),
    )
    conn.commit()
    conn.close()


def fetch_entry(content_id):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    row = conn.execute(
        "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


def fetch_log(limit=20):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_certificate(content_id):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    row = conn.execute(
        "SELECT * FROM certificates WHERE content_id = ?", (content_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


def store_certificate(certificate_id, content_id, creator_id,
                      human_statement, issued_at, verified_label):
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """INSERT INTO certificates
           (certificate_id, content_id, creator_id, human_statement,
            issued_at, verified_label)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (certificate_id, content_id, creator_id,
         human_statement, issued_at, verified_label),
    )
    conn.commit()
    conn.close()


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True) or {}
    creator_id = data.get("creator_id", "anonymous").strip()
    content_type = data.get("content_type", "text").strip().lower()

    if content_type not in ("text", "metadata"):
        return jsonify({"error": "content_type must be 'text' or 'metadata'"}), 400

    content_id = str(uuid.uuid4())

    # ── Text pipeline ──────────────────────────────────────────────────────────
    if content_type == "text":
        text = data.get("text", "").strip()
        if not text:
            return jsonify({"error": "text field is required"}), 400
        if len(text) < 20:
            return jsonify({"error": "text is too short for meaningful analysis (minimum 20 characters)"}), 400

        llm_score = llm_signal(text)
        stylo_score = stylo_signal(text)
        burst_score = burstiness_signal(text)
        confidence = combine_signals(llm_score, stylo_score, burst_score)
        attribution = get_attribution(confidence)
        label = generate_label(attribution, confidence)
        snippet = text[:200]

        log_submission(content_id, creator_id, snippet, "text",
                       attribution, confidence, llm_score, stylo_score,
                       burst_score, label)

        return jsonify({
            "content_id": content_id,
            "content_type": "text",
            "attribution": attribution,
            "confidence": confidence,
            "signals": {
                "llm_score": round(llm_score, 4),
                "stylo_score": round(stylo_score, 4),
                "burstiness_score": round(burst_score, 4),
            },
            "transparency_label": label,
            "status": "classified",
        })

    # ── Metadata pipeline ──────────────────────────────────────────────────────
    metadata = data.get("metadata")
    if not metadata or not isinstance(metadata, dict):
        return jsonify({"error": "metadata object is required when content_type is 'metadata'"}), 400
    if not metadata.get("description") and not metadata.get("title"):
        return jsonify({"error": "metadata must include at least a title or description"}), 400

    meta_llm = metadata_llm_signal(metadata)
    meta_struct = metadata_structural_signal(metadata)
    confidence = combine_metadata_signals(meta_llm, meta_struct)
    attribution = get_attribution(confidence)
    label = generate_label(attribution, confidence)
    snippet = f"[metadata] title={metadata.get('title', '')!r}"

    log_submission(content_id, creator_id, snippet, "metadata",
                   attribution, confidence, meta_llm, meta_struct,
                   None, label)

    return jsonify({
        "content_id": content_id,
        "content_type": "metadata",
        "attribution": attribution,
        "confidence": confidence,
        "signals": {
            "llm_score": round(meta_llm, 4),
            "structural_score": round(meta_struct, 4),
        },
        "transparency_label": label,
        "status": "classified",
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if not reasoning:
        return jsonify({"error": "creator_reasoning is required"}), 400

    entry = fetch_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404

    if entry["status"] == "under_review":
        return jsonify({
            "message": "An appeal has already been filed for this content.",
            "status": "under_review",
        }), 200

    update_appeal(content_id, reasoning)

    return jsonify({
        "message": "Your appeal has been received. This content is now under human review.",
        "content_id": content_id,
        "original_attribution": entry["attribution"],
        "status": "under_review",
    })


@app.route("/certify", methods=["POST"])
def certify():
    """
    Provenance Certificate: a creator completes a human-attestation step by
    providing a signed statement that they are the human author. The system
    issues a certificate with a distinct verified label that is stored
    alongside — not replacing — the automated classification.
    """
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id", "").strip()
    creator_id = data.get("creator_id", "").strip()
    human_statement = data.get("human_statement", "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if len(human_statement) < 20:
        return jsonify({"error": "human_statement is required (minimum 20 characters)"}), 400

    entry = fetch_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404

    if get_certificate(content_id):
        return jsonify({"error": "A provenance certificate already exists for this content."}), 409

    cert_id = str(uuid.uuid4())
    issued_at = datetime.now(timezone.utc).isoformat()
    effective_creator = creator_id or entry["creator_id"]

    verified_label = (
        f"[VERIFIED HUMAN AUTHOR — Certificate {cert_id[:8]}]\n"
        f"The creator has completed a human-attestation verification step for this submission. "
        f"Creator's signed statement: \"{human_statement}\"\n"
        f"Issued: {issued_at[:10]} to creator '{effective_creator}'.\n"
        f"Automated classification on file: {entry['attribution']} "
        f"(confidence {round(entry['confidence'] * 100)}%). "
        f"This certificate is an additional layer of context shown to readers "
        f"alongside the automated result — it does not override the classification."
    )

    store_certificate(cert_id, content_id, effective_creator,
                      human_statement, issued_at, verified_label)

    return jsonify({
        "certificate_id": cert_id,
        "content_id": content_id,
        "creator_id": effective_creator,
        "issued_at": issued_at,
        "verified_label": verified_label,
        "message": "Provenance certificate issued. Your verified human-authorship label is now attached to this content.",
    })


@app.route("/content/<content_id>", methods=["GET"])
def get_content(content_id):
    """Returns the full audit entry plus certificate status for a given content_id."""
    entry = fetch_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404
    cert = get_certificate(content_id)
    return jsonify({
        "entry": entry,
        "certificate": cert,
    })


@app.route("/analytics", methods=["GET"])
def analytics():
    """
    Analytics dashboard: 3 metrics over all submissions.
    1. Detection pattern — ratio of AI vs human vs uncertain verdicts.
    2. Appeal rate — fraction of submissions that have been appealed.
    3. Average confidence by attribution — how certain the system is within each category.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    total = conn.execute("SELECT COUNT(*) FROM audit_log").fetchone()[0]
    if total == 0:
        conn.close()
        return jsonify({"total_submissions": 0, "message": "No data yet."})

    # Metric 1: detection pattern
    detection_pattern = {}
    for row in conn.execute(
        "SELECT attribution, COUNT(*) as cnt FROM audit_log GROUP BY attribution"
    ):
        detection_pattern[row["attribution"]] = {
            "count": row["cnt"],
            "percentage": round(row["cnt"] / total * 100, 1),
        }

    # Metric 2: appeal rate
    appealed = conn.execute(
        "SELECT COUNT(*) FROM audit_log WHERE status = 'under_review'"
    ).fetchone()[0]

    # Metric 3: average confidence by attribution
    avg_confidence = {}
    for row in conn.execute(
        "SELECT attribution, AVG(confidence) as avg_c FROM audit_log GROUP BY attribution"
    ):
        avg_confidence[row["attribution"]] = round(row["avg_c"], 4)

    conn.close()

    return jsonify({
        "total_submissions": total,
        "detection_pattern": detection_pattern,
        "appeal_rate": {
            "appealed_count": appealed,
            "total": total,
            "rate_percent": round(appealed / total * 100, 1),
        },
        "avg_confidence_by_attribution": avg_confidence,
    })


@app.route("/log", methods=["GET"])
def get_log():
    limit = request.args.get("limit", 20, type=int)
    entries = fetch_log(limit)
    return jsonify({"entries": entries, "count": len(entries)})


@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({
        "error": "Rate limit exceeded.",
        "detail": "Submissions are capped at 10 per minute and 100 per day. Please wait before trying again.",
    }), 429


if __name__ == "__main__":
    # Port 5000 is reserved by macOS AirPlay Receiver; use 5001 by default
    port = int(os.environ.get("PORT", 5001))
    app.run(debug=True, port=port)
